server:
  port: 9007
spring:
  application:
    name: leadnews-search
  redis:
    host: 192.168.200.130
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  kafka:
    bootstrap-servers: 192.168.200.130:9092
    #    producer:
    #      ack: 1
    #      retries: 10
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${spring.application.name}-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1s
    listener:
      missing-topics-fatal: false

#自定义elasticsearch连接配置
elasticsearch:
  host: 192.168.200.130
  port: 9200